// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/documentai/v1/document_processor_service.proto

package com.google.cloud.documentai.v1;

public interface ReviewDocumentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.documentai.v1.ReviewDocumentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An inline document proto.
   * </pre>
   *
   * <code>.google.cloud.documentai.v1.Document inline_document = 4;</code>
   * @return Whether the inlineDocument field is set.
   */
  boolean hasInlineDocument();
  /**
   * <pre>
   * An inline document proto.
   * </pre>
   *
   * <code>.google.cloud.documentai.v1.Document inline_document = 4;</code>
   * @return The inlineDocument.
   */
  com.google.cloud.documentai.v1.Document getInlineDocument();
  /**
   * <pre>
   * An inline document proto.
   * </pre>
   *
   * <code>.google.cloud.documentai.v1.Document inline_document = 4;</code>
   */
  com.google.cloud.documentai.v1.DocumentOrBuilder getInlineDocumentOrBuilder();

  /**
   * <pre>
   * Required. The resource name of the HumanReviewConfig that the document will be
   * reviewed with.
   * </pre>
   *
   * <code>string human_review_config = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The humanReviewConfig.
   */
  java.lang.String getHumanReviewConfig();
  /**
   * <pre>
   * Required. The resource name of the HumanReviewConfig that the document will be
   * reviewed with.
   * </pre>
   *
   * <code>string human_review_config = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for humanReviewConfig.
   */
  com.google.protobuf.ByteString
      getHumanReviewConfigBytes();

  public com.google.cloud.documentai.v1.ReviewDocumentRequest.SourceCase getSourceCase();
}
