// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/documentai/v1/document_processor_service.proto

package com.google.cloud.documentai.v1;

public interface ReviewDocumentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.documentai.v1.ReviewDocumentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The Cloud Storage uri for the human reviewed document.
   * </pre>
   *
   * <code>string gcs_destination = 1;</code>
   * @return The gcsDestination.
   */
  java.lang.String getGcsDestination();
  /**
   * <pre>
   * The Cloud Storage uri for the human reviewed document.
   * </pre>
   *
   * <code>string gcs_destination = 1;</code>
   * @return The bytes for gcsDestination.
   */
  com.google.protobuf.ByteString
      getGcsDestinationBytes();
}
